[theme]
primaryColor = "#D72638"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f7"
textColor = "#000000"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = false