OPENAI_API_KEY = "your-openai-key"
CENSUS_API_KEY = "your-census-key"
GOOGLE_API_KEY = "your-google-key"
SUPABASE_URL = "your-supabase-url"
SUPABASE_KEY = "your-supabase-key"
STRIPE_API_KEY = "your-stripe-key"
STRIPE_PRODUCT_PRICE_ID = "your-stripe-price-id"
