OPENAI_API_KEY = "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"
CENSUS_API_KEY = "1cf284aa4eea3bf3e58110d278b0275ca5d8bb82"
GOOGLE_API_KEY = "AIzaSyBw7DibVl36C6vpc7XTxQtc9GNkl5reZG8"
SUPABASE_URL = "https://ttjmxelgjneriqajelfr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0am14ZWxnam5lcmlxYWplbGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDIzNDUsImV4cCI6MjA2ODE3ODM0NX0.njGs4i5CZU1-f2aZU0YXUxmGrsvBI8LSxOYDP437bsQ"
STRIPE_API_KEY = "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"
STRIPE_PRODUCT_PRICE_ID = "prod_SgahGGoWI2uFE8"
